### PR TITLE
Fix #417 Added html lang attribute

### LINKED ISSUE #417: add [lang] attribute to html element
this is an a11y issue, we need to add [lang] attribute to html element.

### PR DESCRIPTION
**Pull request by tylersocholotuik**
## What issue is this referencing?

#417

html-lang

## Do these code changes work locally and have you tested that they fix the issue yourself?

-   [x] yes!

## Does the following command run without warnings or errors?

-   [x] yes! `npm run pr-checks`

## Have you taken a look at our [contributing guidelines](https://github.com/devedmonton/DES-Website/blob/main/.github/CONTRIBUTING.md)?

-   [x] yes!

## My node version matches the one suggested when running `nvm use`?

-   [x] yes!

### CODE REVIEW

**Review by arashsheyda — APPROVED** [review]
LGTM! but I'm not sure if we should use `en` or `en_CA`
\cc @MandyMeindersma @DerrykBoyd @dgmouris

**Comment by DerrykBoyd** [comment]
> LGTM! but I'm not sure if we should use `en` or `en_CA`
> \cc @MandyMeindersma @DerrykBoyd @dgmouris 

I think the correct format is `en-CA` (hyphen separated) but yes I would vote for that

**Comment by tylersocholotuik** [comment]
> > LGTM! but I'm not sure if we should use `en` or `en_CA`
> > \cc @MandyMeindersma @DerrykBoyd @dgmouris 
> 
> I think the correct format is `en-CA` (hyphen separated) but yes I would vote for that

If I make the change to en-CA, do I need to make a new pull request, or can I simply edit the file in this PR? I apologize, I am very new to this.

**Comment by DerrykBoyd** [comment]
> > > LGTM! but I'm not sure if we should use `en` or `en_CA`
> > > \cc @MandyMeindersma @DerrykBoyd @dgmouris 
> > 
> > I think the correct format is `en-CA` (hyphen separated) but yes I would vote for that
> 
> If I make the change to en-CA, do I need to make a new pull request, or can I simply edit the file in this PR? I apologize, I am very new to this. 

You can for sure edit the file in this PR @tylersocholotuik thanks!

**Comment by tylersocholotuik** [comment]
Ok, I made the change to en-CA. Thanks for the tips!

**Comment by arashsheyda** [comment]
thanks @tylersocholotuik 

@allcontributors add @tylersocholotuik for code

**Pull request merged**
