### PR TITLE
Removing the slack from yegwit that was accidentally added years ago

### LINKED ISSUE #195: YEGWIT shouldn't have a slack link
They never had one, this was accidentally copied years ago

### PR DESCRIPTION
**Pull request by MandyMeindersma**
They don't have a public slack

## What issue is this referencing?

this pr fixes #195 

## Have you run the linting command in the `README.md`?

-   [x ] yes! `npm run lint-check`

## Have you taken a look at our [contributing guidelines](https://github.com/devedmonton/DES-Website/blob/main/.github/CONTRIBUTING.md)?

-   [x ] yes!

## My node version matches the one suggested when running `nvm use`?

-   [ x] yes!

### CODE REVIEW

**Review by deejayjay — APPROVED** [review]
Looks good!

**Review by deejayjay — APPROVED** [review]
Looks good!

**Comment by MandyMeindersma** [comment]
@allcontributors add @deejayjay as a reviewer

**Comment by MandyMeindersma** [comment]
@allcontributors add @deejayjay as a review

**Pull request merged**
