### PR TITLE
Testcases: Added testcases for TheMenu Component

### PR DESCRIPTION
**Pull request by NitinRamnani**
## What issue is this referencing?

Added testcases for TheMenu Component and improved code coverage.

## Does the following command run without warnings or errors?

-   [x] yes! `npm run pr-checks`

## Have you taken a look at our [contributing guidelines](https://github.com/devedmonton/DES-Website/blob/main/.github/CONTRIBUTING.md)?

-   [x] yes!

## My node version matches the one suggested when running `nvm use`?

-   [x] yes!

### CODE REVIEW

**Review by MandyMeindersma — APPROVED** [review]

**Review by MandyMeindersma — APPROVED** [review]

**Comment by MandyMeindersma** [comment]
Thank you so much @NitinRamnani! We love people adding tests!

**Comment by MandyMeindersma** [comment]
@all-contributors add @NitinRamnani for test

**Comment by MandyMeindersma** [comment]
@NitinRamnani hey okay so when I merged this in I thought the errors in the build were from my bad internet but they weren't it looks like. 

image


This error started because of these changes, I am trying to figure out why...

cc @DerrykBoyd

**Comment by DerrykBoyd** [comment]
> @NitinRamnani hey okay so when I merged this in I thought the errors in the build were from my bad internet but they weren't it looks like.
> 
> image
> 
> This error started because of these changes, I am trying to figure out why...
> 
> cc @DerrykBoyd

There's really nothing in these changes that could possibly cause a mixed content error. It just looks to me that Netlify has stopped reporting this.

As for why, I'm not entirely sure, I don't think we have any mixed-content. I'll reach out on their support forum see if we can get any tips there.

**Comment by DerrykBoyd** [comment]
OK I have opened a thread here https://answers.netlify.com/t/builds-stopped-reporting-mixed-content/103565 will post back with any details. 

I went through all the netlify settings and I can't see anything we might be able to do for this from our end. 

I did try clearing the build cache, but I'm not sure if that worked or not.

**Comment by MandyMeindersma** [comment]
thank you 🙏

**Pull request merged**
