### PR TITLE
added flutter as meetup

### PR DESCRIPTION
**Pull request by tdenis29**
## What issue is this referencing?
https://github.com/devedmonton/DES-Website/issues/448

## Do these code changes work locally and have you tested that they fix the issue yourself?

-   [x] yes!

## Does the following command run without warnings or errors?

-   [x] yes! `npm run pr-checks`

## Have you taken a look at our [contributing guidelines](https://github.com/devedmonton/DES-Website/blob/main/.github/CONTRIBUTING.md)?

-   [x] yes!

## My node version matches the one suggested when running `nvm use`?

-   [x] yes!

### CODE REVIEW

**Comment by MandyMeindersma** [comment]
Thank you for your contribution @tdenis29 

If you click the details of the build:

image


You can see it failed because of the trailing space: 
image


Delete that and we should be good to merge!

**Comment by tdenis29** [comment]
Hey @MandyMeindersma, Thanks for letting me know, the change has been made.

**Comment by MandyMeindersma** [comment]
@tdenis29 I am not sure I see the change, did the push not go through?

**Comment by tdenis29** [comment]
@MandyMeindersma there we go ! I think it worked this time.

**Review by MandyMeindersma — APPROVED** [review]

**Comment by MandyMeindersma** [comment]
Great job @tdenis29 !!

**Pull request merged**
