### PR TITLE
fix coffee, and moved groups

### PR DESCRIPTION
**Pull request by Jhemming93**

### CODE REVIEW

**Comment by MandyMeindersma** [comment]
Omg look how great it looks: https://deploy-preview-167--dev-edmonton.netlify.app/

this is just the link I grabbed from netlify

**Comment by Jhemming93** [comment]
All i had to do was restart and i fix the problem in 5mins lol

**Comment by Jhemming93** [comment]
this closes #165 and #160

**Review by MandyMeindersma — APPROVED** [review]

**Comment by MandyMeindersma** [comment]
@allcontributors add @Jhemming93 for ideas and code

**Pull request merged**
