### PR TITLE
Fix for v-html lint warning

### PR DESCRIPTION
**Pull request by DerrykBoyd**
## What issue is this referencing?

No linked issue, fix lint warning

## Have you run the linting command in the `README.md`?

-   [x] yes! `npm run lint-check`

## Have you taken a look at our [contributing guidelines](https://github.com/devedmonton/DES-Website/blob/main/.github/CONTRIBUTING.md)?

-   [x] yes!

## My node version matches the one suggested when running `nvm use`?

-   [x] yes!

### CODE REVIEW

**Comment by DerrykBoyd** [comment]
Not sure why the netlify build is failing here.

**Comment by MandyMeindersma** [comment]
maybe if I just restart it, then it will work 🤷 I couldn't figure out why either

**Comment by olimpiuus** [comment]
We have an error during npm run generate.
I think the problem occurs because we inject through {{description}}  HTML text. Just an idea. 

 ```

                    id: 1,
                    name: "Ian Phillipchuck",
                    title: "President",
                    imageLink: "/img/boardPictures/ianPhillipchuck.jpg",
                    description:
                        "Ian Phillipchuk is a Manager, Software Engineering at <a class='text-indigo-600' href='https://getjobber.com/'>Jobber</a>. Professionally, he does Software Consulting, Mobile and Web Development, as well as managing software teams and client projects.<br /><br /> At Dev Edmonton, he wants to grow the society to do more to help all the Devs in Edmonton, from providing resources for Meetups and Conferences for veteran developers, and helping new devs find their way and their first opportunities.<br /><br />Personally, he's probably getting fragged in Destiny 2 PVP for the bajillionth time, or building Lego with his kids.",
                    twitterHandle: "Protagorist",
                    linkedInAccount:
                        "https://www.linkedin.com/in/ian-phillipchuk-69a7009a/",
                    slackAccount: "Ian Phillipchuck",
                }, 

```

**Comment by olimpiuus** [comment]
i miss clicked for closing merge request, sorry

**Comment by olimpiuus** [comment]
Yes , even through npm run build we didn't have error, but our board page is not working properly. 

Screenshot 2023-08-27 at 11 36 00 AM

**Comment by DerrykBoyd** [comment]
Right, I think I remember this now from years ago, we can't render the description like this since it has link tags in it. Will disable the lint warning and add a comment instead.

**Review by MandyMeindersma — APPROVED** [review]

**Comment by MandyMeindersma** [comment]
You're my hero for fixing this one

**Pull request merged**
