### PR TITLE
chore: update dependencies

### LINKED ISSUE #404: NPM dependency warnings
First time running the project in a while as been busy with family 😄 

When getting setup again, I can see a lot of warnings on the `npm install` step around:

- dependency conflicts
- unsupported node engine
- security warnings

Would be prudent to clean these up and possibly, once it's clean add a PR check to make sure new PR's don't introduce any new warnings.

### PR DESCRIPTION
**Pull request by arashsheyda**
## What issue is this referencing?

this PR
- updates the dependencies to latest version
- replaces `nuxt-icon` with `@nuxt/icon` and installs the necessary icon packages
- update the node version
- lint
- fix the security issues suggested by npm (npm audit fix)

closes #404

## Do these code changes work locally and have you tested that they fix the issue yourself?

-   [x] yes!

## Does the following command run without warnings or errors?

-   [x] yes! `npm run pr-checks`

## Have you taken a look at our [contributing guidelines](https://github.com/devedmonton/DES-Website/blob/main/.github/CONTRIBUTING.md)?

-   [x] yes!

## My node version matches the one suggested when running `nvm use`?

-   [x] yes!

### CODE REVIEW

**Comment by MandyMeindersma** [comment]
I assume the logos aren't showing up cause something is weird with netlify? 
image

**Comment by arashsheyda** [comment]
@MandyMeindersma yes probably (it's working for me tho)

Screenshot 2024-10-14 at 7 30 20 PM

**Comment by MandyMeindersma** [comment]
ohhhhh they loaded for me eventually, I might just have bad internet right now

**Review by MandyMeindersma — APPROVED** [review]

**Review by DerrykBoyd — APPROVED** [review]
This is great, thanks @arashsheyda !

**Comment by DerrykBoyd** [comment]
> ohhhhh they loaded for me eventually, I might just have bad internet right now

It wasn't your internet. They didn't load for me first time I landed on the deploy preview, I checked the console and it said they all timed out loading. Hopefully just a weird deploy preview thing.

**Comment by MandyMeindersma** [comment]
yeah they load fine on the real site for me

**Pull request merged**
