### PR TITLE
Remove Intuit from list of Edmonton companies

### LINKED ISSUE #387: Remove Intuit from list of Edmonton companies
Intuit is no longer operating out of Edmonton. Let's remove them from the list of local companies.

Screenshot showing where this needs to be removed:
remove-here

### PR DESCRIPTION
**Pull request by acenasir**
## What issue is this referencing?

this PR closes #387

## Do these code changes work locally and have you tested that they fix the issue yourself?

-   [x] yes!

## Does the following command run without warnings or errors?

-   [x] yes! `npm run pr-checks`

## Have you taken a look at our [contributing guidelines](https://github.com/devedmonton/DES-Website/blob/main/.github/CONTRIBUTING.md)?

-   [x] yes!

## My node version matches the one suggested when running `nvm use`?

-   [x] yes!

### CODE REVIEW

**Comment by arashsheyda** [comment]
@acenasir thank you for your contribution! just some points:
- could you please choose a proper title for the issue? (you can even use the same title as issue)
- and don't remove the template of PR, you have to check them... (and make sure to reference the related issue in there)

thanks

**Comment by acenasir** [comment]
Updated Title as requested - @arashsheyda

**Comment by acenasir** [comment]
Could you elaborate on the second issue? @arashsheyda

**Comment by arashsheyda** [comment]
@acenasir thank you! I updated it (https://github.com/devedmonton/DES-Website/pull/403#issue-2581773748, when you open a PR there is a template text I was referring to that)

**Review by arashsheyda — APPROVED** [review]
looks great! thank you

**Comment by arashsheyda** [comment]
@allcontributors add @acenasir for code

**Pull request merged**
