### PR TITLE
Updating the roles on the board to be more accurate

### PR DESCRIPTION
**Pull request by MandyMeindersma**
## What issue is this referencing?

no issue, from meeting minutes
## Do these code changes work locally and have you tested that they fix the issue yourself?

-   [x] yes!

## Does the following command run without warnings or errors?

-   [x] yes! `npm run pr-checks`

## Have you taken a look at our [contributing guidelines](https://github.com/devedmonton/DES-Website/blob/main/.github/CONTRIBUTING.md)?

-   [x] yes!

## My node version matches the one suggested when running `nvm use`?

-   [x] yes!

### CODE REVIEW

**Comment by DerrykBoyd** [comment]
@MandyMeindersma sorry, just saw this. Do you have any idea what it up with the deploy here?

**Comment by DerrykBoyd** [comment]
> @MandyMeindersma sorry, just saw this. Do you have any idea what it up with the deploy here?

Cache issue I guess, was able to get it to build on Netlify. LGTM

**Review by DerrykBoyd — APPROVED** [review]

**Comment by MandyMeindersma** [comment]
oh yeah weird, thank you

**Comment by MandyMeindersma** [comment]
woops, apparently it's not okay :P I get the same weird errors on the prod build, I'll look into it 🤷

**Pull request merged**
