### PR TITLE
Add leslie to the board page

### PR DESCRIPTION
**Pull request by leslietech**
## What issue is this referencing?
Added Leslie to the board page.

## Do these code changes work locally and have you tested that they fix the issue yourself?

-   [✔] yes!

## Does the following command run without warnings or errors?

-   [✔] yes! `npm run pr-checks`

## Have you taken a look at our [contributing guidelines](https://github.com/devedmonton/DES-Website/blob/main/.github/CONTRIBUTING.md)?

-   [✔] yes!

## My node version matches the one suggested when running `nvm use`?

-   [✔] yes!

### CODE REVIEW

**Comment by MandyMeindersma** [comment]
Weird that the build failed. If you click details you will be able to see the error. I haven't seen that one before, I'll try to look into it but I might get you to try to look into it too cause I still am coughing a little :P

**Comment by leslietech** [comment]
Could it be that this PR depends on PR #305 going through first? I removed Lauren in that PR before adding myself in this PR. Get well soon, hydrate and have something with lemons in it, be it water or tea. Soup also goes a long way.

**Comment by MandyMeindersma** [comment]
No that shouldn't matter. The builds are both failing for the same reason. Something about an AWS lamda which means something is being weird with netlify

**Comment by leslietech** [comment]
This is getting closer to the margins of my scope...lol, however, having looked into this further, it seems as if the Lambda JS Runtime version 14.x was deprecated on December 4, 2023, and updates to existing functions that use 14.x were scheduled to be blocked on Feb 8, 2024 on Lambda https://aws.amazon.com/blogs/compute/managing-aws-lambda-runtime-upgrades. Although the DES website project/repo is using v18.17.0, the Lambda JS Runtime specified in our Netlify deployment is nodejs14.x. Could this be it?

**Comment by MandyMeindersma** [comment]
Good find! Yeah that would make sense. 

So I tried changing the node version on netlify: 
image

And then I tried updating all our references to Node 14 in my test pr but that build still failed because it says we are using node 14 somewhere....

image


but where lol

**Comment by leslietech** [comment]
I just logged into Netlify to check. Please checkout the Environmental Variables. There is an AWS_LAMBDA_JS_RUNTIME key. In it are 4 secrets. This key has 4 contexts which contain the "nodejs14.x" value. I think that this should be "node18js.x" https://app.netlify.com/sites/dev-edmonton/configuration/env#environment-variables

**Comment by MandyMeindersma** [comment]
See you're the expert here. That worked perfectly. Great Job Leslie!

I kicked off the build and it worked but it doesn't show that here so you might have to open a new pr?

Also I might make you open a new pr anyways cause I want to try to only have one commit per pr. See how yours has commits that have already been merged into main but the diff doesn't show them? if you rebase or reset those should go away. Let me know if you need a couple more tips :)

**Comment by leslietech** [comment]
Am glad that it worked :). Let me retry the PR.

**Pull request closed without merging**
