### PR TITLE
Fix broken test setup

### PR DESCRIPTION
**Pull request by DerrykBoyd**
## What issue is this referencing?

None. I saw in a recent MR comment that the test setup was broken. This adds back a working test setup with a single test to demonstrate it's working.

Can be used to unit test our vue components.

## Have you run the linting command in the `README.md`?

-   [x] yes! `npm run lint-check`

## Have you taken a look at our [contributing guidelines](https://github.com/devedmonton/DES-Website/blob/main/.github/CONTRIBUTING.md)?

-   [x] yes!

## My node version matches the one suggested when running `nvm use`?

-   [x] yes!

### CODE REVIEW

**Review by MandyMeindersma — APPROVED** [review]

**Comment by MandyMeindersma** [comment]
fix the merge conflicts and we should be good :)

**Comment by olimpiuus** [comment]
@DerrykBoyd , thank you for migration! Old ava.setup isn't compatible with nuxt 3. Because of it's dependencies.

**Review by MandyMeindersma — APPROVED** [review]

**Comment by MandyMeindersma** [comment]
Wait why did they all fail? It was passing before?

**Comment by DerrykBoyd** [comment]
I've handled the PR conflicts, but there's an issue here with netlify running the vitest tests. Will put this on hold for now until I have a bit of time to look into it.

**Comment by DerrykBoyd** [comment]
Huh, I was able to rerun it fine on Netlify with a clean cache. But that didn't update the checks here. I guess netlify just didn't like that we changed the package.json inbetween deploys. I'm not sure tbh, no reason the new commit should fail.

**Pull request merged**
