### PR TITLE
set fixed width on button with responsive adjustment

### LINKED ISSUE #321: Width of button is a little off
The width of this button on the homepage looks a little weird to me but I can't decide how to fix it. Make the text inside just needs to be centered? Maybe it needs to have a fixed width? not sure. Here are some screenshots:

image

image

image

### PR DESCRIPTION
**Pull request by jsc215**
## What issue is this referencing?

this fixes #321 
## Do these code changes work locally and have you tested that they fix the issue yourself?

-   [x ] yes!

## Does the following command run without warnings or errors?

-   [ x] yes! `npm run pr-checks`

## Have you taken a look at our [contributing guidelines](https://github.com/devedmonton/DES-Website/blob/main/.github/CONTRIBUTING.md)?

-   [ x] yes!

## My node version matches the one suggested when running `nvm use`?

-   [ x] yes!

### CODE REVIEW

**Comment by MandyMeindersma** [comment]
Thanks so much @jsc215 ! I love it. 

I think we must have configured our linter weird, so I want to try to change it before we merge this in (we just changed to a new linting method, thank you for being our guinea pig). Unless this is your editors linting?

I am not on my machine until Tuesday though (going to view the eclipse! 🌞 ) so it might be until then until I can debug. Sorry!

**Comment by arashsheyda** [comment]
@jsc215 great work, thanks!

@MandyMeindersma the stylistic of eslint module is false by default (I thought it was true by default, sorry) I'll open a PR asap and after that we can merge this PR.

**Comment by jsc215** [comment]
> @jsc215 great work, thanks!
> 
> @MandyMeindersma the stylistic of eslint module is false by default (I thought it was true by default, sorry) I'll open a PR asap and after that we can merge this PR.

you're very welcome!

**Comment by MandyMeindersma** [comment]
Thanks to @arashsheyda our linting should be fixed now! 

I think if you run `npm run lint:fix` it should auto fix? but if now maybe copy your changes to a new branch! Thanks again for being our guinea pig @jsc215

**Comment by MandyMeindersma** [comment]
Hey @jsc215  I would still love to have your contribution so if you want to run the linting command that would be great, other wise I will merge this into another branch and then commit the linting errors then merge that (that way we still have your commit and work recorded!) 😄

**Review by arashsheyda — APPROVED** [review]

**Review by MandyMeindersma — APPROVED** [review]

**Comment by MandyMeindersma** [comment]
@arashsheyda saved us again with the auto linting bot! Thank you 

@allcontributors add @jsc215 for code

**Pull request merged**
