### PR TITLE
Fix a couple of typos and grammar errors

### PR DESCRIPTION
**Pull request by paul-mcaviney**

### CODE REVIEW

**Comment by MandyMeindersma** [comment]
hahah thank you @paul-mcaviney 

I think you have to run prettier for the build to pass (you should be able to click on the "details" tab on netlify to see where it failed
)

**Comment by MandyMeindersma** [comment]
@arashsheyda do you want to bring these changes into yours? I might merge this one before yours cause it's easier 🙈

**Comment by arashsheyda** [comment]
@MandyMeindersma yea for sure! (I will change it once this is merged, thanks)

thanks @paul-mcaviney

**Comment by paul-mcaviney** [comment]
> hahah thank you @paul-mcaviney
> 
> I think you have to run prettier for the build to pass (you should be able to click on the "details" tab on netlify to see where it failed)
> 
> So we are so picky about formatting

Oh, whoops! Sorry! I didn't download anything locally and just fixed the typos on Github directly. I'm still fairly new to making contributions anywhere. Next time I wanna contribute I'll download locally and run through prettier :)

**Pull request closed without merging**
