### PR TITLE
fix bug with not closing mob nav menu

### LINKED ISSUE #186: When I click on an item in the menu, the menu doesn't collapse
So on tablet and mobile, if I open the menu (hamburger button) and then I click on a section, it brings me to the correct section but it doesn't close the menu

### PR DESCRIPTION
**Pull request by olimpiuus**
## What issue is this referencing?

this pr fixes #186 
"When I click on an item in the menu, the menu doesn't collapse #186"

## Have you run the linting command in the `README.md`?

-   [ v] yes! `npm run lint-check`

## Have you taken a look at our [contributing guidelines](https://github.com/devedmonton/DES-Website/blob/main/.github/CONTRIBUTING.md)?

-   [v ] yes!

## My node version matches the one suggested when running `nvm use`?

-   [v ] yes!

### CODE REVIEW

**Comment by olimpiuus** [comment]
ugly but working. By the way this one is easiest path.

**Comment by MandyMeindersma** [comment]
Okay so two things:

first, something looks very off in the preview:
image


The other thing is that I am realizing that this was working with the `<a>` tags, I mean I agree that the whole thing that we should follow the SPA standards but it is a pretty light fast site. The extra reload wouldn't matter if we are running into so many other issues. 

Thoughts?

**Review by MandyMeindersma — CHANGES_REQUESTED** [review]
Needs some styling changes? Or maybe we just go back to no nuxt-links?

**Comment by olimpiuus** [comment]
i quite confuse about reloading web page , didnt catch why we need it.  For now tag a will not route us anywhere, its just holder and hadler for menu closing. We can change it for div, will be no differnce. Better leave nuxt -links with divs or a inside it to handle logic.

 About styling, it looks weird. I coudnt find problem, on my  mac it works fine. Is it Windows or Android? 

Screenshot 2023-08-03 at 10 41 38 PM

**Comment by olimpiuus** [comment]
above i add funcionality to close mobile menu by click outside menu itself. same file , related bug.

**Comment by MandyMeindersma** [comment]
image


So you see in the build instructions? click "details" and it will bring you to this pr as a build. Thats where you should see the weird styling.

Cause it looks like it still happens On the netlify build

**Review by MandyMeindersma — CHANGES_REQUESTED** [review]
Css changes?

**Comment by olimpiuus** [comment]
> 

tag a just makes mess inside nuxt link. so i wrap it by <li>

**Review by MandyMeindersma — APPROVED** [review]
Looks great! Thank you for doing so much work back and forth!

**Pull request merged**
