### PR TITLE
Updates the default layout and TheFooter so that footer color will be…

### PR DESCRIPTION
**Pull request by deejayjay**
Completes #193 
- Updates the default layout and TheFooter so that footer color will be different in All Events and All Resources pages
- Updates the background color for All Events and All Resources pages

### CODE REVIEW

**Comment by MandyMeindersma** [comment]
Oh shoot, I should have been more clear in the issue. I think you are right, changing the footer based on the page seems weird. I thinking making it blue accoss all pages is the way to go

**Comment by MandyMeindersma** [comment]
The footer looks great on the community events and resources page though

**Comment by deejayjay** [comment]
> Oh shoot, I should have been more clear in the issue. I think you are right, changing the footer based on the page seems weird. I thinking making it blue accross all pages is the way to go

@MandyMeindersma: Alright. I will revert the code that makes footer theme dynamic, and make the footer light blue all across the app later in the evening. Thanks

**Comment by MandyMeindersma** [comment]
Sorry! Thank you!

**Comment by deejayjay** [comment]
> Sorry! Thank you!

No worries. That was a quick fix, and I also learned something while implementing it :).

**Pull request merged**
