### PR TITLE
fix: update twitter to X #328

### PR DESCRIPTION
**Pull request by jeevikasirwani**
changed the logo and name

### CODE REVIEW

**Review by MandyMeindersma — APPROVED** [review]

**Comment by MandyMeindersma** [comment]
Thank you @jeevikasirwani 

We have been playing around with our linting (sorry to change in in the middle of your pr)

Do you mind re linting and then I'll merge?

**Comment by MandyMeindersma** [comment]
oh or `npm run lint:fix` should fix it :)

**Comment by jeevikasirwani** [comment]
> oh or `npm run lint:fix` should fix it :)

IN MY FORK BRANCH RIGHT?

**Comment by MandyMeindersma** [comment]
absolutely :)

**Comment by MandyMeindersma** [comment]
Hey @jeevikasirwani  I would still love to have your contribution so if you want to run the linting command that would be great, other wise I will merge this into another branch and then commit the linting errors then merge that (that way we still have your commit and work recorded!) 😄

**Comment by MandyMeindersma** [comment]
@arashsheyda saved us again with the auto linting bot! Thank you

@allcontributors add @jeevikasirwani  for code

**Pull request merged**
