### PR TITLE
Add minimal setup for vite-pwa/nuxt

### PR DESCRIPTION
**Pull request by DerrykBoyd**
## Do these code changes work locally and have you tested that they fix the issue yourself?

-   [x] yes!

## Does the following command run without warnings or errors?

-   [x] yes! `npm run pr-checks`

## Have you taken a look at our [contributing guidelines](https://github.com/devedmonton/DES-Website/blob/main/.github/CONTRIBUTING.md)?

-   [x] yes!

## My node version matches the one suggested when running `nvm use`?

-   [x] yes!

### CODE REVIEW

**Comment by DerrykBoyd** [comment]
Quick note, we are missing the correct icon sizes for the web app manifest. I used the largest icon in the public folder 180x180 but we might want to add some 256x256 or 512x512 icons

**Comment by arashsheyda** [comment]
this is great thank you! what do you think of adding an alert to notify user about PWA (to install or reaload or ...)

for reference: https://github.com/vite-pwa/nuxt/blob/main/playground/layouts/default.vue

**Review by arashsheyda — APPROVED** [review]

**Review by arashsheyda — APPROVED** [review]
this is great thank you! what do you think of adding an alert to notify user about PWA (to install or reaload or ...)

for reference: https://github.com/vite-pwa/nuxt/blob/main/playground/layouts/default.vue

**Comment by DerrykBoyd** [comment]
> this is great thank you! what do you think of adding an alert to notify user about PWA (to install or reaload or ...)
> 
> for reference: https://github.com/vite-pwa/nuxt/blob/main/playground/layouts/default.vue

I think that's probably overkill for the type of site we have since it's mostly informational.

**Pull request merged**
