### PR TITLE
Fix(#378): Squish meetups and events 

### PR DESCRIPTION
**Pull request by AACHAL2303PATIL**
### Changes Made
- Consolidated the list of events into the existing meetup page.
- Updated the events page to display a calendar format.

### Testing
- Verified that all events are correctly displayed on the meetup page.
- Ensured that the calendar functionality on the Events page is working as expected.
- Checked for any layout or design issues after merging the content.

### Checklist
- [ ] Code changes are well-documented.
- [ ] All new and existing tests passed.
- [ ] UI/UX has been reviewed and approved.
- [ ] Changes are consistent with project guidelines.
- [ ] Merge conflicts have been resolved.

Screenshot 2024-09-29 131513
Screenshot 2024-09-29 132040

### CODE REVIEW

**Comment by Anubhav2k3** [comment]
Please assign this issue to me. I've already made a pull request addressing it.

**Comment by AACHAL2303PATIL** [comment]
Please assign this issue to me. I've already made a pull request addressing it.

**Review by MandyMeindersma — CHANGES_REQUESTED** [review]
Great work! two things:

one: Would you do me a huge favour and rename the title on the meetup page from "Meetups We Support" to "Local Tech Meetups"

two: Sorry I could have been more clear in the ticket but since you are moving all the data over from meetups, I think the events objects and anywhere it is referenced should be deleted too. :)

**Comment by MandyMeindersma** [comment]
@AACHAL2303PATIL I can only assign you if you comment on it: https://github.com/devedmonton/DES-Website/issues/378

**Comment by MandyMeindersma** [comment]
Hey @AACHAL2303PATIL hows it going?

Did you want any advice on how to get this merged in? Thanks so much again!

**Comment by MandyMeindersma** [comment]
Since it has been 2 weeks since there has been any changes I am going to close this pr. Let me know if you want to still work on it and I can reassign you

**Pull request closed without merging**
