### PR TITLE
Added Changes From Discussion

### PR DESCRIPTION
**Pull request by kodyVS**
## What issue is this referencing?
No issue reference but adding changes from the discussion

## Do these code changes work locally and have you tested that they fix the issue yourself?

-   [x] yes!

## Does the following command run without warnings or errors?

-   [x] yes! `npm run pr-checks`

## Have you taken a look at our [contributing guidelines](https://github.com/devedmonton/DES-Website/blob/main/.github/CONTRIBUTING.md)?

-   [x] yes!

## My node version matches the one suggested when running `nvm use`?

-   [x] yes!

### CODE REVIEW

**Comment by MandyMeindersma** [comment]
Did you want events and resources in both menu's?

**Comment by DerrykBoyd** [comment]
I'm out of the loop for the discussions referenced, but this looks good to me 👍

**Review by DerrykBoyd — APPROVED** [review]

**Comment by MandyMeindersma** [comment]
@kodyVS sorry I gave you merge conflicts, once we figure out what actually goes into the menu then this looks good from me too

**Comment by kodyVS** [comment]
No problem.

The navigation in the home sub menu goes to the sub-headers on the main page and the main links go to the full pages. 

We could rename the home sub menu sections to get rid of any confusion instead of "Meetups, events and resources" we have "Community" and add "Newsletter" to the list.

**Comment by MandyMeindersma** [comment]
Ooooohhhh woops, my bad, you are right. Yeah this looks good to me!

**Comment by MandyMeindersma** [comment]
Oh one more question, is there a reason you deleted all the unit tests? I think they are still valid ones?

**Comment by kodyVS** [comment]
I deleted the unit tests because I changed the way the menu is displayed to utilize the built-in features of vue and tailwind and in doing so, changed the methods that were in the test. However, I can add 2 more unit tests for the methods I replaced.

**Comment by MandyMeindersma** [comment]
Thank you so much for adding those! I appreciate it! 

Sorry my changes are now breaking your imports :)

**Comment by MandyMeindersma** [comment]
@all-contributors add @kodyVS for code and ideas

**Comment by MandyMeindersma** [comment]
Thank you so much Kody!

**Pull request merged**
