### PR TITLE
refactor: slack orbit icons design

### PR DESCRIPTION
**Pull request by arashsheyda**
## What issue is this referencing?

a cleaner design, and now we can add more icons. any icon suggestions?

here are some icons that I like, jsut because of their design and colour haha
- Docker
- AWS
- Google Cloud
- GraphQL
- MongoDB
- TailwindCSS
-  Viest / Playwright
- Redis
- Firebase

should we add them?

Screenshot 2024-12-03 at 4 17 35 PM

## Do these code changes work locally and have you tested that they fix the issue yourself?

-   [x] yes!

## Does the following command run without warnings or errors?

-   [x] yes! `npm run pr-checks`

## Have you taken a look at our [contributing guidelines](https://github.com/devedmonton/DES-Website/blob/main/.github/CONTRIBUTING.md)?

-   [x] yes!

## My node version matches the one suggested when running `nvm use`?

-   [x] yes!

### CODE REVIEW

**Comment by DerrykBoyd** [comment]
Is it meant to be cut off at the bottom like that? I think the previous version where it's in the centered looks better

**Comment by arashsheyda** [comment]
@DerrykBoyd yes, this way we get more space on top, but we can make it centred again

**Comment by DerrykBoyd** [comment]
> @DerrykBoyd yes, this way we get more space on top, but we can make it centred again

More space for what purpose? Looks like in your screenshot that's just white space now above. I don't care too much either way, I guess was just making sure it wasn't a mistake. But if that's intentional then all good.

**Comment by arashsheyda** [comment]
@DerrykBoyd more space for the text, `to say Hi` could be a line or two for example

**Comment by DerrykBoyd** [comment]
> @DerrykBoyd more space for the text, `to say Hi` could be a line or two for example

Personally I would just get rid of that text and center the radial icons, there is already a wall of text just to the side of the slack window image.

I'll approve so you are not blocked and you can make the final call.

**Review by DerrykBoyd — APPROVED** [review]

**Comment by arashsheyda** [comment]
@DerrykBoyd Ah yes, I agree. centred looks better 😄
do you think we should add more icons?

Screenshot 2024-12-04 at 10 25 02 AM

**Comment by DerrykBoyd** [comment]
> @DerrykBoyd Ah yes, I agree. centred looks better 😄
> do you think we should add more icons?
> 
> Screenshot 2024-12-04 at 10 25 02 AM
> 

Nope, there's a lot on there 😂

**Comment by arashsheyda** [comment]
@MandyMeindersma, yes we can add different speeds for each circle. we can remove it, but I'm in favour of keeping it, I can make it a bit bigger, or the DES logo smaller haha

**Comment by MandyMeindersma** [comment]
Oh actually one other thing, the first time I visit the page I only get one logo:

image
image

**Comment by MandyMeindersma** [comment]
> @MandyMeindersma, yes we can add different speeds for each circle. we can remove it, but I'm in favour of keeping it, I can make it a bit bigger, or the DES logo smaller haha

Yeah maybe make it a bit bigger? I wouldn't want to make the des logo any smaller

**Comment by MandyMeindersma** [comment]
Also also did we want to change it on mobile? I think it might be too small?

Original:
image


With your changes:
image

**Comment by arashsheyda** [comment]
@MandyMeindersma
- the icons not showing up is because of the build, it would work when deployed.
- sure!
- I tried to adjust the sizing on mobile, but yeah it looks small 😄 , so the old concept (jsut showing the DES logo on mobile) is okay?

**Comment by MandyMeindersma** [comment]
>so the old concept (jsut showing the DES logo on mobile) is okay?

Perfect!

Thank you so much!!

**Comment by dgmouris** [comment]
@arashsheyda Great work on this I think it's awesome.

I've also queried my open source club and they also think it's very cool (emphasis on very)

I endorse this change!

**Review by dgmouris — APPROVED** [review]
I think we should merge this!

**Comment by arashsheyda** [comment]
@dgmouris thank you so much :))) I'll try to fix the screen size in mobile by the end of today and I think then we're good to go?

**Comment by MandyMeindersma** [comment]
The logo isn't showing up for me on mobile, is that a weird netlify thing?

**Comment by arashsheyda** [comment]
@MandyMeindersma no I didn't add it (white looked better 😄)

**Review by MandyMeindersma — APPROVED** [review]

**Pull request merged**
