### PR TITLE
URL updated

### LINKED ISSUE #245: Change our expiring slack link
https://join.slack.com/t/devedmonton/shared_invite/zt-24bp1mmie-XdXUv1eYy4MRElmXZaoqdg

### PR DESCRIPTION
**Pull request by shassshank**
fixed #245

### CODE REVIEW

**Comment by MandyMeindersma** [comment]
Oh wow, I didn't realize we had so many locations of the same link. Do you want to try putting these all into one variable? I know it wasn't part of the ticket but if you wanted to try that would be appreciated

**Comment by MandyMeindersma** [comment]
Please always tag me as well as @alex-wilmer :)

**Review by MandyMeindersma — APPROVED** [review]

**Comment by MandyMeindersma** [comment]
@shassshank any time you are tagging me can you also tag @alex-wilmer and @deejayjay (so add them as reviewers too)

also now you can add @dcampelld and @thinkstylestudio now too :)

**Comment by MandyMeindersma** [comment]
@alex-wilmer @dcampbelld @thinkstylestudio 

Can I have one more pair of eyes on this before I merge?

**Review by dcampbelld — APPROVED** [review]
@MandyMeindersma Everything looks good to me!

**Comment by MandyMeindersma** [comment]
@all-contributors add @shassshank for code

**Pull request merged**
