### PR TITLE
(Fix #379)Added bsides to meetups

### LINKED ISSUE #379: Add bsides to events/meetups
Add https://www.bsidesedmonton.org/ to events and meetups.

image:
https://ik.imagekit.io/des/events/bsides.png

### PR DESCRIPTION
**Pull request by blizet**
What issue is this referencing?
This PR is referencing https://github.com/devedmonton/DES-Website/issues/379 , which adds "Bsides Edmonton" to the list of meetups.

Do these code changes work locally and have you tested that they fix the issue yourself?
yes!
Does the following command run without warnings or errors?
yes! npm run pr-checks
Have you taken a look at our [contributing guidelines](https://github.com/devedmonton/DES-Website/blob/main/.github/CONTRIBUTING.md)?
yes!
My node version matches the one suggested when running nvm use?
yes!

### CODE REVIEW

**Comment by MandyMeindersma** [comment]
Hey @blizet thank you! I am still seeing some wordpress stuff unfortunately though. Let me know if you have any questions about how to get rid of those files

**Comment by blizet** [comment]
Surely would help a lot

**Comment by MandyMeindersma** [comment]
Hey @blizet absolutely! Thank you for your contributions

So because you have so many commits on this branch I think it might make it easier to start with a new branch. To do that I would:

1. Copy and paste the code you added for bsides
2. Checkout the master branch (the master of the dev edmonton fork, not your master fork)
3. Make a new branch
4. Copy and paste your changes

Another more complicated way to do this would be to "rebase". Rebasing is harder (it would be hard for me to explain over text, normally I explain it in person) but it's a fun thing to learn if you wanted to google it and play around

**Comment by blizet** [comment]
Thank you for your support in this process! I apologize for any inconvenience it may have caused.

**Pull request closed without merging**
