### PR TITLE
rearranged logos into folders - Rearrenge logos #208

### LINKED ISSUE #208: Rearrenge logos
Inside public/img/logos we have a big mess 😢. 
Need to rearrange these logos into at least three folders: meetups, resources and events. Update paths in components/MeetupsSection.vue, store/events.js and store/resources.js. 
Screenshot 2023-08-26 at 11 00 17 AM

### PR DESCRIPTION
**Pull request by innith**
## Have you run the linting command in the `README.md`?

-   [x] yes! `npm run lint-check`

## Have you taken a look at our [contributing guidelines](https://github.com/devedmonton/DES-Website/blob/main/.github/CONTRIBUTING.md)?

-   [x] yes!

## My node version matches the one suggested when running `nvm use`?

-   [ ] yes!

### CODE REVIEW

**Comment by olimpiuus** [comment]
@innith , Thanks for an excellent job! Appreciate 😄

**Review by olimpiuus — APPROVED** [review]

**Review by olimpiuus — APPROVED** [review]

**Comment by olimpiuus** [comment]
I have checked pr. Please merge @MandyMeindersma.

**Review by MandyMeindersma — APPROVED** [review]

**Comment by MandyMeindersma** [comment]
@allcontributors add @innith for code

**Comment by MandyMeindersma** [comment]
@allcontributors add @olimpiuus for bugs

Because of all the issues that you made yesterday 💪

**Comment by MandyMeindersma** [comment]
@allcontributors add @olimpiuus for bugs

**Pull request merged**
