### PR TITLE
chore: UI improvments

### PR DESCRIPTION
**Pull request by arashsheyda**
## What issue is this referencing?

this PR improves the couloring in dark mode, and fixes some minor UI problems (sorry it kinda got into me, I didn't open an issue first)

| Before | After |
|--------|-------|
| Screenshot 2024-10-24 at 8 36 43 PM | Screenshot 2024-10-24 at 8 37 04 PM |

## Do these code changes work locally and have you tested that they fix the issue yourself?

-   [x] yes!

## Does the following command run without warnings or errors?

-   [x] yes! `npm run pr-checks`

## Have you taken a look at our [contributing guidelines](https://github.com/devedmonton/DES-Website/blob/main/.github/CONTRIBUTING.md)?

-   [x] yes!

## My node version matches the one suggested when running `nvm use`?

-   [x] yes!

### CODE REVIEW

**Review by dgmouris — APPROVED** [review]
Totally fine not to open an issue on this one, I'm good with these changes 

Thanks @arashsheyda

**Comment by arashsheyda** [comment]
thanks @dgmouris

**Comment by johnjovero98** [comment]
I really like the detail of putting the "Dev Edmonton Society" on that purple chip!

**Suggestion:** I would recolor the button on light mode

| before | after |
|---|---|
|  Screenshot 2024-10-25 at 1 40 22 PM | Screenshot 2024-10-25 at 1 37 35 PM |

(frontend and UX/UI talks, amiright 👀)

**Comment by arashsheyda** [comment]
@johnjovero98 nice catch! will do, thanks

**Review by DerrykBoyd — APPROVED** [review]

**Review by MandyMeindersma — APPROVED** [review]

**Comment by MandyMeindersma** [comment]
LOVE

**Pull request merged**
